"""add ondelete cascade

Revision ID: 9cb1089a9def
Revises: 99d831242adc
Create Date: 2023-09-07 16:41:33.481740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb1089a9def'
down_revision = '99d831242adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint('transactions_account_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'accounts', ['account_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transactions_account_id_fkey', 'accounts', ['account_id'], ['id'])
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
