"""check

Revision ID: 8fea492c979b
Revises: b94a2128932b
Create Date: 2023-09-07 15:52:18.244089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fea492c979b'
down_revision = 'b94a2128932b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('idx_accounts_number')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_transactions_account')
        batch_op.drop_constraint('transactions_account_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_foreign_key('transactions_account_id_fkey', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_transactions_account', ['company_id', 'account_number', 'txn_id'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('idx_accounts_number', ['company_id', 'number'], unique=False)

    # ### end Alembic commands ###
